name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: MetadataApp.sln
      # Define a reliable, absolute path for the output package
      Package_Output_Path: ${{ github.workspace }}\AppPackages

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    - name: Build and create the MSIX package
      # This command now uses the absolute path variable
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:AppxPackageDir="${{ env.Package_Output_Path }}" /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false

    - name: Upload build artifacts
      # The upload action now looks in that same reliable path
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Package_Output_Path }}\**\*.msix
