name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: MetadataApp.sln
      # The main project's path
      App_Project_Path: MetadataApp\MetadataApp.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    # This step now builds the main project directly to create the package
    - name: Build the application and create package
      run: msbuild $env:App_Project_Path /p:Configuration=Release /p:AppxPackageDir="..\AppPackages" /p:AppxPackageSigningEnabled=false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: AppPackages
