name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish the application
      run: dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:AppxPackageSigningEnabled=false

    # --- THIS IS THE ONLY STEP THAT MATTERS NOW ---
    - name: List all files to find the package
      run: dir /s
      shell: cmd
