name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish the application
      run: dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:AppxPackageSigningEnabled=false

    # --- THE FINAL FIX ---
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Application-Files
        # This path correctly uploads the entire 'publish' folder
        path: '**/publish'
